version: "3"
services:
    orchestrator:
        build:
            context: .
            dockerfile: Dockerfile-orchestrator
        networks:
            - backend
        ports:
            - 8080:8080
        environment:
            - 'MODE=master'
            - 'REDIS_URL=redis://redis'
            - 'WORKER=http://worker:8080/jobs'

    worker:
        build:
            context: .
            dockerfile: Dockerfile-worker
        networks:
            - backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
            - ./lib/sitespeedConfig.json:/opt/sitespeedDefaultConfig.json

    graphite:
        image: graphiteapp/graphite-statsd:1.1.6-1
        networks:
            - backend
        ports:
            - 8081:80
            - 2003-2004:2003-2004
            - 2023-2024:2023-2024
            - 8125:8125/udp
            - 8126:8126

    grafana:
        image: grafana/grafana:6.5.1-ubuntu
        ports:
            - 3000:3000
        networks:
            - backend

    redis:
        image: redis:5.0.7
        networks:
            - backend

networks:
    backend:
